#!/usr/bin/env node
'use strict'

const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const serverSource = fs.readFileSync(path.join(__dirname, '../../packages/ui/server.js'), 'utf8')
const deployScript = fs.readFileSync(path.join(__dirname, '../../scripts/deploy-pull-reload.sh'), 'utf8')

test('server exposes guarded deploy reload API', () => {
  assert.match(serverSource, /app\.get\('\/api\/system\/deploy\/status'/)
  assert.match(serverSource, /app\.get\('\/api\/system\/deploy\/log'/)
  assert.match(serverSource, /DEPLOY_LOG_FILE/)
  assert.match(serverSource, /tail \|\| 20000/)
  assert.match(serverSource, /app\.post\('\/api\/system\/deploy\/reload'/)
  assert.match(serverSource, /confirm.*pull-and-reload/s)
  assert.match(serverSource, /SECOND_BRAIN_DEPLOY_TOKEN/)
  assert.match(serverSource, /disabled until SECOND_BRAIN_DEPLOY_TOKEN is configured/)
  assert.match(serverSource, /secureTokenEqual\(expectedToken, suppliedToken\)/)
  assert.match(serverSource, /req\.get\('x-deploy-token'\)/)
  assert.doesNotMatch(serverSource, /req\.body\?\.deploy_token/)
  assert.match(serverSource, /deployAlreadyRunning\(\)/)
  assert.match(serverSource, /SECOND_BRAIN_DEPLOY_INSTALL/)
  assert.match(serverSource, /req\.body\?\.install === true \? '1' : '0'/)
})

test('deploy reload script is fast-forward only and restarts UI listeners', () => {
  assert.match(deployScript, /git fetch origin "\$BRANCH"/)
  assert.match(deployScript, /git pull --ff-only origin "\$BRANCH"/)
  assert.match(deployScript, /git status --porcelain/)
  assert.match(deployScript, /SECOND_BRAIN_DEPLOY_INSTALL/)
  assert.match(deployScript, /write_status "running" "install" "Installing npm dependencies"/)
  assert.match(deployScript, /npm install 2>&1 \| tee -a "\$LOG_FILE"/)
  assert.match(deployScript, /npm run build --workspace=packages\/ui/)
  assert.match(deployScript, /lsof -ti tcp:4000/)
  assert.match(deployScript, /lsof -ti tcp:4001/)
  assert.match(deployScript, /deploy-ui-api\.pids/)
  assert.match(deployScript, /append_ancestors/)
  assert.match(deployScript, /com\.secondbrain\.ui/)
  assert.match(deployScript, /launchctl print "\$LAUNCHD_TARGET"/)
  assert.match(deployScript, /launchctl kickstart -k "\$LAUNCHD_TARGET"/)
  assert.match(deployScript, /nohup node packages\/ui\/server\.js/)
  assert.match(deployScript, /nohup npm start --workspace=packages\/ui/)
  assert.match(deployScript, /SECOND_BRAIN_DEPLOY_VERIFY_TIMEOUT_SECONDS/)
  assert.match(deployScript, /SECOND_BRAIN_DEPLOY_STABILITY_SECONDS/)
  assert.match(deployScript, /api\/health/)
  assert.match(deployScript, /127\.0\.0\.1:4000/)
  assert.match(deployScript, /while \[ "\$SECONDS" -lt "\$VERIFY_DEADLINE" \]/)
})
